workflows:
  ios:
    name: iOS Workflow
    instance_type: mac_mini
    max_build_duration: 60  # Максимальное время сборки
    environment:
      vars:
        MY_VAR: 'value'  # Переменные окружения, если нужно
    scripts:
      # Шаг 1: Устанавливаем зависимости (если они есть)
      - name: Install dependencies
        script: |
          # Если у вас есть файл Podfile для CocoaPods
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      # Шаг 2: Резолвим зависимости через Swift Package Manager
      - name: Resolve Swift dependencies
        script: |
          swift package resolve

      # Шаг 3: Сборка проекта через Swift Package Manager
      - name: Build project with Swift Package Manager
        script: |
          swift build

      # Шаг 4: Тестирование (если нужно)
      - name: Run tests
        script: |
          swift test
