workflows:
  ios:
    name: iOS Build and Deploy
    environment:
      xcode: latest  # Использовать последнюю стабильную версию Xcode с встроенным Swift
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          swift package resolve  # Это разрешит зависимости Swift
      - name: Build the app
        script: |
          echo "Building the app..."
          swift build  # Стандартная команда для сборки проекта с помощью Swift
