workflows:
  ios:
    name: Build iOS App with Swift Package Manager
    max_build_duration: 60
    scripts:
      # Устанавливаем зависимости через Swift Package Manager
      - name: Install dependencies with SPM
        script: |
          swift package resolve

      # Сборка проекта через Swift Package Manager
      - name: Build the app
        script: |
          swift build

      # Архивирование проекта (если нужно)
      - name: Archive the app
        script: |
          # Пример использования Xcode для архивирования
          xcodebuild archive -scheme my-swift-project -sdk iphoneos -archivePath $PWD/build/my-swift-project.xcarchive

    artifacts:
      - $PWD/build/my-swift-project.xcarchive
