workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    environment:
      xcode: latest  # Указываем, что используем Xcode для сборки
    scripts:
      - name: Install dependencies
        script: |
          # Установки зависимостей с использованием CocoaPods, если они есть
          echo "No dependencies for Swift project"
      - name: Build the app
        script: |
          # Сборка проекта с использованием Xcode и создания архива .ipa
          xcodebuild clean archive \
            -workspace "my-swift-project.xcworkspace" \
            -scheme "my-swift-project" \
            -sdk iphoneos \
            -archivePath "$PWD/build/my-swift-project.xcarchive"
      - name: Export IPA
        script: |
          # Экспорт .ipa файла из .xcarchive
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/my-swift-project.xcarchive" \
            -exportOptionsPlist "$PWD/my-swift-project/ExportOptions.plist" \
            -exportPath "$PWD/build/ios/iphoneos"
    artifacts:
      - build/ios/iphoneos/*.ipa  # Указываем путь для артефактов
