workflows:
  ios_build:
    name: iOS build
    max_build_duration: 120
    environment:
      vars:
        XCODE_VERSION: "13.2.1"
        FLUTTER_CHANNEL: "stable"
    scripts:
      - name: Install dependencies
        script: |
          git clone https://github.com/flutter/flutter.git /flutter
          export PATH=$PATH:/flutter/bin
          flutter doctor
      - name: Build app
        script: |
          swift build
      - name: Export IPA
        script: |
          xcodebuild archive -scheme "my-swift-project" -workspace "my-swift-project.xcworkspace" -sdk iphoneos -archivePath $CM_BUILD_DIR/my-swift-project.xcarchive
