workflows:
  ios:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      vars:
        FLAVOR: 'production'
      xcode: latest  # Используем последнюю версию Xcode
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install || echo "No Pods to install"

      - name: Build and Test
        script: |
          xcodebuild -workspace my-swift-project.xcworkspace -scheme my-swift-project clean build | tee result.log

    artifacts:
      - build/ios/ipa/*.ipa  # Кодемэджик сам найдёт .ipa
