workflows:
  ios:
    name: Build iOS app without Xcode project
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          # Установки зависимостей для Swift (если есть)
          echo "No dependencies for Swift project"
      - name: Build the app
        script: |
          # Сборка приложения с использованием Swift команд
          swift build
    artifacts:
      - build/ios/iphoneos/*.ipa
