workflows:
  ios:
    name: iOS Workflow
    instance_type: mac_mini
    max_build_duration: 60  # Максимальное время сборки
    environment:
      vars:
        MY_VAR: 'value'  # Переменные окружения, если нужно

    # Этапы скриптов сборки
    scripts:
      # Шаг 1: Устанавливаем зависимости с помощью Swift Package Manager
      - name: Resolve Swift dependencies
        script: |
          swift package resolve

      # Шаг 2: Сборка проекта через Swift Package Manager
      - name: Build project with Swift Package Manager
        script: |
          swift build

      # Шаг 3: Архивация приложения с использованием xcodebuild
      - name: Archive app with xcodebuild
        script: |
          xcodebuild archive -scheme my-swift-project -sdk iphoneos -archivePath $PWD/build/my-swift-project.xcarchive

      # Шаг 4: Экспорт IPA
      - name: Export IPA from archive
        script: |
          xcodebuild -exportArchive -archivePath $PWD/build/my-swift-project.xcarchive -exportOptionsPlist $PWD/ExportOptions.plist -exportPath $PWD/build

      # Шаг 5: Загрузка IPA как артефакт сборки
      - name: Upload IPA as build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-swift-project.ipa
          path: $PWD/build/my-swift-project.ipa
