workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build the app
        script: |
          # Сборка проекта с использованием Xcode и создания архива .ipa
          xcodebuild clean archive \
            -project "my-swift-project.xcodeproj" \
            -scheme "my-swift-project" \
            -sdk iphoneos \
            -archivePath "$PWD/build/my-swift-project.xcarchive"
      - name: Export IPA
        script: |
          # Экспорт .ipa файла из .xcarchive
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/my-swift-project.xcarchive" \
            -exportPath "$PWD/build/ios/iphoneos"
    artifacts:
      - build/ios/iphoneos/*.ipa  # Указываем путь для артефактов
