name: Build and Export iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Устанавливаем нужную версию Xcode
      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v2
        with:
          xcode-version: '16.2'  # Укажите нужную версию Xcode

      # 3. Устанавливаем зависимости через CocoaPods (если используете их)
      - name: Install CocoaPods dependencies
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      # 4. Сборка проекта с использованием xcodebuild (build)
      - name: Build with xcodebuild
        run: |
          xcodebuild clean build -project my-swift-project/my-swift-project.xcodeproj -scheme my-swift-project -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 14'

      # 5. Архивируем проект с помощью xcodebuild (archive)
      - name: Archive with xcodebuild
        run: |
          xcodebuild archive -project my-swift-project/my-swift-project.xcodeproj -scheme my-swift-project -sdk iphoneos -archivePath $PWD/build/my-swift-project.xcarchive

      # 6. Экспортируем IPA из архива (экспорт)
      - name: Export IPA with xcodebuild
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/my-swift-project.xcarchive -exportPath $PWD/build -exportOptionsPlist exportOptions.plist

      # 7. Загружаем артефакт IPA
      - name: Upload IPA as build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-swift-project.ipa
          path: $PWD/build/my-swift-project.ipa
